#define LED_Level1_ON     3   
#define LED_Level1_OFF    2    
#define LED_Level2_ON     5
#define LED_Level2_OFF    4    
#define LED_Level3_ON     9
#define LED_Level3_OFF    8    
#define LED_Level4_ON    18
#define LED_Level4_OFF   16    
#define LED_Level5_ON    38
#define LED_Level5_OFF   16    
#define LED_Level6_ON    78 
#define LED_Level6_OFF   60    
#define LED_Level7_ON   156
#define LED_Level7_OFF  120     